trigger:
  branches:
    include:
      - master
  paths:
    include:
      - IntelliTect.TestTools.Selenate/*
      - selenate-pipeline.yml

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/IntelliTect.TestTools.Selenate.slnf'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '2.1.0'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use latest NuGet'

- task: NuGetCommand@2
  displayName: 'Restore Solution'
  inputs:
    restoreSolution: '**/IntelliTect.TestTools.sln'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:Version=$(version)'

- task: DotNetCoreCLI@2
  displayName: 'Pack Selenate Project'
  inputs:
    command: 'custom'
    projects: '**/IntelliTect.TestTools.Selenate.csproj'
    custom: 'pack'
    arguments: '-p:Version="$(version)-ci-$(Build.BuildId)" -c Release -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Package'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Selenate'
    publishLocation: 'Container'